services:
  daphne-local:
    build: .
    image: daphne:local
    container_name: daphne-local
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    env_file:
      - ./.daphne.local.env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./.daphne.config.local.toml:/app/config.toml:ro
  telegram-bot-api:
    image: mirror.gcr.io/aiogram/telegram-bot-api:10.1
    container_name: daphne-telegram-bot-api
    restart: unless-stopped
    env_file:
      - ./.daphne.local.env
    environment:
      TELEGRAM_LOCAL: "1"
      TZ: Asia/Tokyo
    ports:
      - "8081:8081"
    tmpfs:
      - /var/lib/telegram-bot-api
