version: '3.8'

services:
  daphne:
    build: .
    image: daphne:latest
    container_name: daphne
    restart: always
    environment:
      - DAPHNE_BOT_TOKEN=$DAPHNE_BOT_TOKEN
      - DAPHNE_DATABASE_URL=/data/daphne.db
      - DAPHNE_RBAC_CONFIG_PATH=/config/rbac.toml
      - DAPHNE_NOTIFICATION_CHANNEL=$DAPHNE_NOTIFICATION_CHANNEL
      - DAPHNE_IMAGE_CHANNEL=$DAPHNE_IMAGE_CHANNEL
    volumes:
      - ./config:/config
      - ./data:/data
