apiVersion: v1
kind: ConfigMap
metadata:
  name: daphne-config
  namespace: harus-media
data:
  config.toml: |
    [app]
    telegram_api_url = "http://localhost:8081"
    video_upload_limit_mb = 512

    [rbac]
    public_commands = ["help"]

    [rbac.roles.admin]
    permissions = ["*"]

    [rbac.roles.standard_group]
    permissions = ["fix"]

    [rbac.users]
    996596491 = "admin" # Owner

    [rbac.chats]
    # average anime fan boy
    -1002058191932 = "standard_group"
    # michishirube
    -1002101328553 = "standard_group"
    # harus_channel
    -1003438236939 = "standard_group"
    # harus_notification
    -1003524535102 = "standard_group"
