version: "3.6"

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ROOT_PASSWORD=${ETCD_PASS}
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - etcd_data:/bitnami/etcd/data
    networks:
      - daphne_network

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - daphne_network

volumes:
  etcd_data:
    driver: local
  redis_data:
    driver: local

networks:
  daphne_network:
    driver: bridge
